### ISSUE TITLE
Still not able to get it work.

### ISSUE THREAD

**Issue by frank777777777** [lambdalisue/vim-pyenv#31]
I have been through lots of hours trying to get the jedi-vim omni completion and goto to work in pyenv environment. I came to this plugin and it still not work for me.
I use vim 8.1 with vundle. I installed the vim-pyenv with vundle, and made sure to put vim-pyenv after jedi-vim. After installing with `PlugInstall`, I go to my project folder, activated my pyenv with `pyenv local scrapper`. In vim, I use `:PyenvActivate scrapper`, it shows `vim-pyenv: "3.6.0/envs/scrapper" is activated`.
However, the omni-completion and goto still use the system site-package instead of the one in pyenv.
Any idea how should I debug this?

My python and pip version works with pyenv, its just the site-package not working.

**Comment by frank777777777** [comment]
I got it working after using `let g:jedi#force_py_version=3`, but here is what happened before that.
I installed python 3.6.0 in pyenv. 
* The output of `:python3 print(sys.version)` shows 3.5.2, however `:python3 --version` shows 3.6.0
* `:python3 print(sys.path)` gives me correct path, which is in pyenv.
* After simply :PyenvActivate scrapper, my `:JediDebugInfo` gives me, which didn't work:
```
##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.5.2 (default, Nov 23 2017, 16:37:01), [GCC 5.4.0 20160609]`
 - global site module: `/usr/lib/python3.5/site.py`

##### Jedi

 - path: `/home/yili/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.12.1

##### Jedi environment: <Environment: 3.5.2 in /usr>

 - executable: /usr/bin/python3.5
 - sys_path:
    - `/usr/local/lib/python3.5/dist-packages/pudb-2017.1.4-py3.5.egg`
    - `/usr/local/lib/python3.5/dist-packages/Pygments-2.2.0-py3.5.egg`
    - `/usr/local/lib/python3.5/dist-packages/urwid-2.0.1-py3.5-linux-x86_64.egg`
    - `/usr/lib/python35.zip`
    - `/usr/lib/python3.5`
    - `/usr/lib/python3.5/plat-x86_64-linux-gnu`
    - `/usr/lib/python3.5/lib-dynload`
    - `/home/yili/.local/lib/python3.5/site-packages`
    - `/usr/local/lib/python3.5/dist-packages`
    - `/usr/lib/python3/dist-packages`

```

In fact, simply using `let g:jedi#force_py_version=3` works for me, without even using this plugin..
```
##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.5.2 (default, Nov 23 2017, 16:37:01), [GCC 5.4.0 20160609]`
 - global site module: `/usr/lib/python3.5/site.py`

##### Jedi

 - path: `/home/yili/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.12.1

##### Jedi environment: <SameEnvironment: 3.5.2 in /usr>

 - executable: /home/yili/.pyenv/shims/python3
 - sys_path:
    - `/home/yili/.pyenv/versions/3.6.0/lib/python36.zip`
    - `/home/yili/.pyenv/versions/3.6.0/lib/python3.6`
    - `/home/yili/.pyenv/versions/3.6.0/lib/python3.6/lib-dynload`
    - `/home/yili/.pyenv/versions/scrapper/lib/python3.6/site-packages`

##### Known environments

 - <Environment: 3.5.2 in /usr> (/usr/bin/python3.5)
 - <Environment: 2.7.15 in /usr> (/usr/bin/python2.7)

```
